<?php
/**
 * Copyright © Magepotato. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Backend\Block\Template $block */

use \Magento\Cms\Model\Page as CmsPage;
use \Magento\Cms\Model\Block as CmsBlock;

$availableImportTypes = [
    CmsPage::CACHE_TAG => __('Pages'),
    CmsBlock::CACHE_TAG => __('Blocks'),
];









?>
<h3><?=__('Import Content')?></h3>
<div id="content_import" class="magepotato">
    <form action="<?php echo $block->getUrl('magepotato/toolbox/import'); ?>" method="post" enctype="multipart/form-data">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <input type="file" name="import_file" />
        <select name="import_type">
            <?php foreach ($availableImportTypes as $key => $value) : ?>
                <option value="<?=$key?>"><?=$value?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit" class="action-default primary" value="Submit">
            <?= $block->escapeHtml(__('Run')) ?>
        </button>
    </form>
</div>
